-- phpMyAdmin SQL Dump
-- version 4.9.5deb2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Aug 16, 2022 at 08:59 AM
-- Server version: 8.0.30-0ubuntu0.20.04.2
-- PHP Version: 8.0.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `centproDB`
--

-- --------------------------------------------------------

--
-- Table structure for table `promo`
--

CREATE TABLE `promo` (
  `id` bigint UNSIGNED NOT NULL,
  `id_website` int DEFAULT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `img` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `end_date` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `link` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `location` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `category` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `discount` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `start_date` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maskapai` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lokasi_hotel` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `promo`
--

INSERT INTO `promo` (`id`, `id_website`, `name`, `img`, `end_date`, `description`, `link`, `created_at`, `updated_at`, `location`, `category`, `discount`, `start_date`, `maskapai`, `lokasi_hotel`) VALUES
(8650, 1, 'Pegipegi Time! Hari Merdeka kasih kamu diskon s.d. 50% untuk semua produk', 'https://www.pegipegi.com/promo/pegipegitime_hutri/flat/img/APP_1200x660.jpg', '2022-08-17', '\nMERDEKA! Dapatkan diskon Pegipegi Time! Hari Merdeka s.d. 50% untuk hotel, tiket pesawat, bus & travel dan kereta api untuk liburan di hari ulang tahun RI dengan lebih hemat! Syarat & ketentuan berlaku.Pegipegi Lagi, Yuk!    \n        ', 'https://www.pegipegi.com/promo/pegipegitime_hutri/', NULL, NULL, '', 'Kosong', '50%', '', '', ''),
(8651, 1, 'Nikmati penawaran diskon Hotel spesial untuk Check-In hari ini ', 'https://www.pegipegi.com/promo/todays_deals/flat/img/E_00284_APP_1200x660.jpg', '', '\n           Butuh liburan atau staycation tapi belum booking hotel? Pegipegi punya solusinya! Check-In hotel sekarang dapatkan harga spesial mulai dari Rp50.000 untuk menginap lebih hemat. Syarat & ketentuan berlaku.\n\nPegipegi Lagi, Yuk!\n          ', 'https://www.pegipegi.com/promo/todays_deals/', NULL, NULL, '', 'Kosong', '', '', '', ''),
(8652, 1, 'Nikmati diskon menginap di IntiWhiz 30% untuk bikin liburanmu jadi lebih hemat', 'https://www.pegipegi.com/promo/intiwhiz_fs/flat/img/APP_1200x660.png', '2022-08-28', '\n\n              Jangan sampai ketinggalan!Flash sale potongan langsung sebesar 30% untuk menginap lebih hemat di hotel Intiwhiz. Nikmati pengalaman menginap yang nyaman maksimal gak pake mahal. Hanya di tanggal 7, 14, 21, dan 28 Agustus, mulai pukul 19.00-23.00 WIB setiap harinya.Pegipegi Lagi, Yuk!\n', 'https://www.pegipegi.com/promo/intiwhiz_fs/', NULL, NULL, '', 'Kosong', '30%', '', '', 'intiwhiz'),
(8653, 1, 'Cek di sini untuk mendapatkan potongan harga langsung sebesar 60% untuk pemesanan hotel-hotel pilihan RedDoorz.', 'https://www.pegipegi.com/promo/reddoorz_deals/flat/img/E_00284_APP_1200x660.jpg', '2022-08-16', '\n            Apa yang udah hemat, jadi makin hemat? Nginep di hotel-hotel pilihan RedDoorz jawabannya. Lagi ada diskon s.d. 50% nih. Tunggu apalagi? Pesan sekarang! Syarat & ketentuan berlaku.\n          ', 'https://www.pegipegi.com/promo/reddoorz_deals/', NULL, NULL, 'Tonga', 'hotel', '60%', '', '', ''),
(8654, 1, 'Nikmati diskon menginap di d’PrimaHotel s.d. 20% untuk liburan yang lebih hemat', 'https://www.pegipegi.com/promo/dprima_deals/flat/img/E_00284_APP_1200x660.jpg', '2022-08-15', '\n            Untuk kamu yang berencana untuk menginap, kamu harus cek diskon d’PrimaHotel s.d. 20% untuk menginap yang lebih hemat! Syarat & ketentuan berlaku.Pegipegi Lagi, Yuk!\n          ', 'https://www.pegipegi.com/promo/dprima_deals/', NULL, NULL, '', 'Kosong', '20%', '', '', ''),
(8655, 1, 'Temukan hotel atau tiket pesawat bertanda AntiBoros, buat dapetin harga termurah* di aplikasi Pegipegi! Traveling yang on budget sekarang jadi gampang banget kan.', 'https://www.pegipegi.com/promo/antiboros/flat/img/E_00284_APP_1200x660.jpg', '', '\n          Yang pengen nginep atau terbang dengan harga termurah, sini kumpuuul! Pegipegi punya sesuatu yang spesial nih buat kamu. Temukan hotel atau tiket pesawat bertanda #AntiBoros, buat dapetin harga termurah* di aplikasi Pegipegi! Traveling yang on budget sekarang jadi gampang banget kan. Jangan lupa cek syarat & ketentuan yang berlaku di bawah ini ya. \n          ', 'https://www.pegipegi.com/promo/antiboros/', NULL, NULL, '', 'flight hotel', '', '', '', ''),
(8656, 1, 'Saatnya Cari Hotel Favorit Lebih Mudah di Akomodasi Favorit!', 'https://www.pegipegi.com/promo/flat/img/campaign/M_0005_APP-1200x660.jpg', '', '\nLiburan di depan mata tapi masih sibuk cari-cari Hotel?\nCari di fitur Akomodasi Favorit di aplikasi Pegipegi! Fitur ini akan memudahkan para pelanggan menemukan hotel-hotel terbaik yang:\n\n Memiliki fasilitas & layanan yang baik\n Memiliki ulasan pelanggan yang baik\n Harga kompetitif\n\nLokasi Akomodasi Favorit tersebar di beberapa destinasi favorit pilihan Pegipegi seperti: Jakarta, Bandung, Jogja, Bali, Malang, Solo, Surabaya, Semarang. Dan segera menyusul destinasi favorit lainnya.\n', 'https://www.pegipegi.com/promo/akom_fav/', NULL, NULL, '', 'Kosong', '', '', '', ''),
(8657, 1, 'Perhatian penumpang Citilink, Garuda Indonesia dan Lion Air: kamu bisa mendapatkan vaksinasi gratis untuk terbang lebih aman & nyaman!', 'https://www.pegipegi.com/promo/vaccine_airlines/m/img/E_00252_APP_1200x660.jpg', '', '\nDapatkan vaksinasi gratis untuk kamu yang terbang dengan maskapai Citilink, Garuda Indonesia atau Lion Air! Bikin pengalaman terbang jadi lebih aman dan nyaman.\n\nDetail syarat & ketentuan masing-masing maskapai, bisa cek di bawah ini ya!\n', 'https://www.pegipegi.com/promo/vaccine_airlines/', NULL, NULL, 'Indonesia', 'health', '', '', 'citilink', ''),
(8658, 1, 'Nikmati diskon hotel & tiket pesawat s.d. Rp750.000 dengan digibank setiap hari Kamis dan Jumat.', 'https://www.pegipegi.com/promo/digibank/flat/img/E_00284_APP_1200x660.jpg', '2022-12-31', '\nSetiap hari Kamis dan Jumat, kamu bisa pakai promo ini untuk merealisasikan mimpimu! Pakai Kartu Kredit digibank untuk mendapatkan diskon hotel & tiket pesawat s.d. Rp750.000. Syarat & ketentuan berlaku.\n          ', 'https://www.pegipegi.com/promo/digibank/', NULL, NULL, '', 'flight hotel', '750.000', '', '', ''),
(8659, 1, 'Karena hari esok pasti lebih baik! Nikmati diskon tiket pesawat & hotel hingga Rp350.000 spesial untuk kamu pengguna kartu kredit TMRW by UOB', 'https://www.pegipegi.com/promo/tmrw/flat/img/E_00284_APP_1200x660.jpg', '', '\n            Spesial untuk kamu pengguna kartu kredit TMRW by UOB, ada diskon tiket pesawat & hotel hingga Rp350.000 loh dari Pegipegi. Ayo, pakai promonya sekarang dan nikmati hari esok yang lebih baik! Syarat & ketentuan berlaku\n\n          ', 'https://www.pegipegi.com/promo/tmrw/', NULL, NULL, '', 'flight hotel', '350.000', '', '', ''),
(8660, 1, 'Nikmati diskon hotel & tiket pesawat s.d. Rp350.000 dengan Kartu Kredit DBS setiap hari Rabu.', 'https://www.pegipegi.com/promo/digibank_visa/flat/img/E_00284_APP_1200x660.jpg', '2022-09-30', '\n           Setiap hari Rabu, kamu bisa pakai promo ini untuk merealisasikan liburan impianmu! Pakai Kartu Kredit digibank VISA untuk mendapatkan diskon hotel & tiket pesawat s.d. Rp350.000. Syarat & ketentuan berlaku.\n\n          ', 'https://www.pegipegi.com/promo/digibank_visa/', NULL, NULL, '', 'flight hotel', '350.000', '', '', ''),
(8661, 1, 'Nikmati diskon s.d. Rp176.000 untuk pesawat atau hotel saat bayar dengan Kartu Debit BNI setiap Jumat!', 'https://www.pegipegi.com/promo/fridaydeals/flat/img/E_00284_APP_1200x660.jpg', '2022-12-31', '\n            Kabar gembira untuk kalian pemegang kartu debit BNI! Karena kamu bisa mendapatkan diskon s.d. Rp176.000 untuk pesawat atau hotel saat melakukan pembayaran dengan Kartu Debit BNI untuk liburan jadi lebih hemat setiap hari Jumat. Syarat & ketentuan berlaku.\n          ', 'https://www.pegipegi.com/promo/fridaydeals/', NULL, NULL, 'Indonesia', 'hotel', '', '', '', ''),
(8662, 1, 'Dapatkan diskon hotel & tiket pesawat s.d. Rp120.000 setiap hari selasa khusus pengguna Kartu Kredit OCBC', 'https://www.pegipegi.com/promo/ocbc/flat/img/E_00284_APP_1200x660.jpg', '', '\n            Yuhuu~ yang seru-seru di setiap hari Selasa? Promo Regular Tuesday OCBC dong pastinya! Dapatkan diskon hotel & tiket pesawat s.d. Rp100.000 setiap hari selasa khusus pengguna Kartu Kredit OCBC NISP. Syarat & ketentuan berlaku.\n\n          ', 'https://www.pegipegi.com/promo/ocbc/', NULL, NULL, '', 'flight hotel', '20.000', '', '', ''),
(8663, 1, 'Dapatkan diskon tiket pesawat Rp100.000 khusus untuk pengguna PermataKartuKredit.', 'https://www.pegipegi.com/promo/permata/flat/img/E_00284_APP_1200x660.jpg', '2022-12-31', '\n            Kabar baik untuk kamu pengguna PermataKartuKredit! Kamu bisa liburan lebih hemat dengan diskon tiket pesawat Rp100.000. Bepergian jadi lebih asik dan murah.Pegipegi Lagi, Yuk!\n\n          ', 'https://www.pegipegi.com/promo/permata/', NULL, NULL, '', 'flight', '100.000', '', '', ''),
(8664, 1, 'Diskon semua produk s.d. Rp70Rb setiap hari, khusus untuk pengguna GoPay', 'https://www.pegipegi.com/promo/gopay/flat/img/E_00284_APP_1200x660.jpg', '2022-12-31', '\n           Kalau kamu sudah pernah pakai Gopay, berarti ini untukmu! Dapatkan diskon hotel, tiket pesawat dan kereta api s.d. Rp70.000 setiap harinya, khusus untuk pengguna Gopay! Syarat & ketentuan berlaku.Pegipegi Lagi, Yuk!\n\n          ', 'https://www.pegipegi.com/promo/gopay/', NULL, NULL, '', 'Kosong', '', '', '', ''),
(8665, 1, 'Beli produk apapun & masukkan kode kuponnya untuk mendapatkan voucher diskon AnterAja senilai Rp25.000, tanpa minimum transaksi.', 'https://www.pegipegi.com/promo/anteraja/m/img/E_00260_APP_1200x660.jpg', '2022-08-31', '\nNikmati keuntungan tambahan saat beli produk apapun di Pegipegi. Masukan kode kupon di bawah ini untuk bisa mendapatkan voucher diskon Anteraja senilai Rp25.000, tanpa minimum transaksi. Liburan lebih hemat, antar barang pun bisa lebih hemat!\n\n\nPeriode Booking\ns.d. 31 Agustus 2022\n\n\nPeriode Keberangkatan\nKapan saja\n\n\nPeriode Inap\nKapan saja\n\n\n', 'https://www.pegipegi.com/promo/anteraja/', NULL, NULL, '', 'Kosong', '', '', '', ''),
(8666, 1, 'Gunakan Kredivo untuk menikmati cicilan 0% untuk pesan tiket pesawat, hotel, kereta api, bus & travel!', 'https://www.pegipegi.com/promo/kredivo_cicilan/flat/img/E_00284_APP_1200x660.jpg', '2022-08-27', '\n            Horee! Nggak usah galau kalau mau transaksi di Pegipegi, karena ada cicilan 0%* tanpa kartu kredit dari Kredivo. Pesan hotel, tiket pesawat, tiket kereta, atau tiket bus & travel jadi makin ringan, deh! Syarat dan ketentuan berlaku.Pegipegi Lagi, Yuk!\n          ', 'https://www.pegipegi.com/promo/kredivo_cicilan/', NULL, NULL, '', 'flight hotel', ' 0%', '', '', ''),
(8667, 1, 'Ajukan Kartu Kredit Digital digibank dan nikmati cashback s.d. Rp1.750.000', 'https://www.pegipegi.com/promo/apply_digibank/flat/img/E_00284_APP_1200x660.jpg', '2022-08-31', '\n            Ajukan Kartu Kredit digital digibank jenis Live Fresh atau Mastercard World Black dan dapatkan Cashback s.d. Rp1.750.000! Syarat & ketentuan berlaku\n          ', 'https://www.pegipegi.com/promo/apply_digibank/', NULL, NULL, '', 'Kosong', '750.000', '', '', ''),
(8668, 1, 'Download Aplikasi & buka tabungan TMRW dengan kode kupon Pegipegi, bonus kupon diskon eksklusif s.d. Rp750.000*, loh. Yuk, ajukan sekarang!', 'https://www.pegipegi.com/promo/apply_uobtmrw/flat/img/E_00284_APP_1200x660.jpg', '2022-08-31', '\n            Rencanakan hari esok yang lebih baik bersama UOB! Spesial buat kamu yang download aplikasi & buka tabungan TMRW dengan kode kupon Pegipegi, ada bonus kupon diskon eksklusif s.d. Rp750.000*, loh. Yuk, ajukan sekarang! Syarat & ketentuan berlaku\n          ', 'https://www.pegipegi.com/promo/apply_uobtmrw/', NULL, NULL, '', 'Kosong', '750.000', '', '', ''),
(8669, 1, 'Saatnya #Nyalakan hidup bersama OCBC! Buka layanan Nyala disertai TAKA/deposito di ONe Mobile dengan kode kupon ONXPEGIPEGI, dan dapatkan kupon diskon liburan s.d. Rp500.000*.', 'https://www.pegipegi.com/promo/apply_ocbcnyala/flat/img/E_00284_APP_1200x660.jpg', '2022-12-31', '\n            Saatnya #Nyalakan hidup bersama OCBC! Buka layanan Nyala disertai TAKA/deposito di ONe Mobile dengan kode kupon ONXPEGIPEGI, untuk mendapatkan kupon diskon liburan hingga Rp500.000*! Syarat & ketentuan berlaku.\n          ', 'https://www.pegipegi.com/promo/apply_ocbcnyala/', NULL, NULL, '', 'Kosong', '500.000', '', '', ''),
(8670, 1, 'Hai Travelers, sekarang makin mudah merencanakan liburan dengan fitur pembayaran cicilan dengan berbagai bank di Pegipegi!', 'https://www.pegipegi.com/promo/flat/img/bank/installment.png', '', 'kosong', 'https://www.pegipegi.com/installment/', NULL, NULL, '', 'Kosong', '', '', '', ''),
(8671, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/original/promo/2022/08/08/0772b64b-6284-4b19-a7bd-df8a6163f43d-1659926459070-0046981aa89c737cba4f564e2237a4f6.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/promo-anniversary', NULL, NULL, '', '', '', '', '', ''),
(8672, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/14/041f593d-4e6d-42dc-9d98-3b63fc9b69da-1660494557959-8ee8e21ce18a6c5d6ccfb771bc48160f.png', '', 'kosong', 'https://www.tiket.com/promo/pesawat/promo-anniversary-pesawat-domestik', NULL, NULL, '', 'flight', '', '', '', ''),
(8673, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/15/5ad4d580-bb31-4cd8-b16c-d92157b4f4ba-1660524176204-3cd7005ac7c1678563a3413585069d69.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/promo-anniversary-hotel-villa-apt', NULL, NULL, '', '', '', '', '', ''),
(8674, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/15/bc57f8da-b495-4b40-a6f2-e8dc4ce65382-1660516297427-0afaff29bc1706f51984862160710f17.png', '', 'kosong', 'https://www.tiket.com/promo/to-do/promo-anniversary-todo-domestik', NULL, NULL, '', '', '', '', '', ''),
(8675, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/14/9ec03c01-d97d-4d77-a1a7-cc5f80bf3898-1660494764046-3f67c4bd9dae0b183018672eb1f33d34.png', '', 'kosong', 'https://www.tiket.com/promo/pesawat/promo-anniversary-pesawat-internasional', NULL, NULL, '', 'flight', '', '', '', ''),
(8676, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/15/870fccd4-26af-418c-9829-2f6196cc0302-1660524252809-587cca121cb49a60cc6d06b7e5446690.png', '', 'kosong', 'https://www.tiket.com/promo/hotel/promo-anniversary-hotel-international', NULL, NULL, '', 'hotel', '', '', '', ''),
(8677, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/15/a4cd97ae-5419-4191-91e7-7acbc2c3c888-1660516486811-81ff11a15487e2cc126cd92b339e3aeb.png', '', 'kosong', 'https://www.tiket.com/promo/to-do/promo-anniversary-todo-internasional', NULL, NULL, '', '', '', '', '', ''),
(8678, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/15/aa2520e6-92a3-4199-b024-ea3fa91cecbb-1660516646770-07d5b88b02b38637b199a85b53985f54.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/promo-anniversary-event', NULL, NULL, '', '', '', '', '', ''),
(8679, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/14/912c3980-415e-4c92-a15c-9bd8e900bb77-1660494947224-a0c72668373b7871be23276c3675d8e8.png', '', 'kosong', 'https://www.tiket.com/promo/kereta-api/promo-anniversary-kereta-api', NULL, NULL, '', 'akomodasi', '', '', 'train', ''),
(8680, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/14/79bd18ae-8d74-4b53-9a16-14e3dae68e4f-1660495220885-07d1cdec665642973fe43fcd8784c5f5.png', '', 'kosong', 'https://www.tiket.com/promo/sewa-mobil/promo-anniversary-sewa-mobil', NULL, NULL, '', 'akomodasi', '', '', 'car', ''),
(8681, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/14/15b9e2b5-c79d-4d81-a441-1bb6f7d1dcd8-1660495367948-25d11006c92b8f1616049e1398c25a09.png', '', 'kosong', 'https://www.tiket.com/promo/airport-transfer/promo-anniversary-airport-transfer', NULL, NULL, '', 'akomodasi', '', '', 'jemput', ''),
(8682, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/21/7fe672e2-97af-4f5c-983c-f27f8a0790e7-1658409290409-0a6698d0f3d72df5081fac78722b5c66.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/international-deals', NULL, NULL, '', '', '', '', '', ''),
(8683, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/03/54470e6c-6830-49f8-979a-ff6591b87c6c-1659495741935-31f5bb70fcbd995f1867b27a0292bee1.png', '', 'kosong', 'https://www.tiket.com/promo/pesawat/promo-pesawat-murah', NULL, NULL, '', 'flight', '', '', '', ''),
(8684, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/29/18a25c86-d581-4690-bac8-22df7309c16e-1659066245236-355d886f7d608375d0c7c0af47e2b346.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/thailand', NULL, NULL, '', '', '', '', '', ''),
(8685, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/27/3533318f-cdc2-4e67-8ce3-b5ea5cdbdc9b-1658897178154-85ecabe6c78593f95c69e0391f6cfbb3.png', '', 'kosong', 'https://www.tiket.com/promo/to-do/tiket-todo-eksklusif', NULL, NULL, '', '', '', '', '', ''),
(8686, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/29/2991225f-e24a-4f9f-9719-e2b67e265f24-1659091520440-4be68beb2252c76454aad7a464def717.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/hotel-partner', NULL, NULL, '', '', '', '', '', ''),
(8687, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/02/0e5e9e5a-a588-40f7-9310-9627af955017-1659425294310-23daf913efb2f726af0128c571e43ed3.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/promo-hotel-partner', NULL, NULL, '', '', '', '', '', ''),
(8688, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/original/promo/2022/07/27/5864fbb8-21a8-4c0a-9f96-82dd0a725389-1658890171990-ec48b4532d2200c02627c342dea3bd7d.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/tiket-paylater', NULL, NULL, '', '', '', '', '', ''),
(8689, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/09/36d1a817-3fbf-4df1-9ebe-3bb298b95d1d-1660029583571-530475d558c42b5247ee42861b917a9e.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/ovo', NULL, NULL, '', '', '', '', '', ''),
(8690, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/21/c88b3eca-21d7-49a0-b36b-a652d84a6305-1658409207515-8d49392818e22b2d4c035128aa337651.png', '', 'kosong', 'https://www.tiket.com/promo/pesawat/sriwijaya-air-nam-air-deals', NULL, NULL, '', 'flight', '', '', '', ''),
(8691, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/29/3d5cdf6c-aed2-4a54-84b3-57a38516fa63-1659063013781-c997b171fe9178e8f471b43b85ada65f.png', '', 'kosong', 'https://www.tiket.com/promo/pesawat/promo-sriwijaya', NULL, NULL, '', 'flight', '', '', '', ''),
(8692, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/25/56662987-78ab-4f1b-844a-212e8f3d342d-1658745537096-2dbc6dc86907e960c816da2e92ad3aeb.png', '', 'kosong', 'https://www.tiket.com/promo/pesawat/tiket-pesawat', NULL, NULL, '', 'flight', '', '', '', ''),
(8693, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/21/a34506b4-b0ce-47b1-b85a-053435fed3bc-1658408419386-6bd7c7b72a8dd3e043d4291c43e58660.png', '', 'kosong', 'https://www.tiket.com/promo/pesawat/special-deals-citilink', NULL, NULL, '', 'flight', '', '', '', ''),
(8694, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/21/b154d369-c2dd-4d70-a5c7-050c8d283463-1658408464174-100a0ed828bdfa2533d555516000c839.png', '', 'kosong', 'https://www.tiket.com/promo/pesawat/special-deals-garuda', NULL, NULL, '', 'flight', '', '', '', ''),
(8695, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/29/a4e741a3-838f-407e-9b0b-3648acd98676-1659091269242-845d5572c3d0c8747d547f908e23dd77.png', '', 'kosong', 'https://www.tiket.com/promo/hotel/hotel-mgm', NULL, NULL, '', 'hotel', '', '', '', ''),
(8696, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/14/cf7c8b74-7b28-493d-af24-2ba7a93e3900-1657796855149-8dd73425e7d59f0541a0c53cd7b58551.png', '', 'kosong', 'https://www.tiket.com/promo/airport-transfer/diskon-car-transfer', NULL, NULL, '', 'akomodasi', '', '', 'jemput', ''),
(8697, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/15/0b22f147-93af-4005-ae75-a2935c2e2f5c-1657876406880-3ef7b13b64bb37352a0ae7531d63bca9.png', '', 'kosong', 'https://www.tiket.com/promo/airport-transfer/airport-transfer-diskon', NULL, NULL, '', 'akomodasi', '', '', 'jemput', ''),
(8698, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/14/1baf1e15-cdd7-4644-aaa0-60b50d99acf4-1657807441751-52d3bf9ce11ab869179d76ef681e8f9a.png', '', 'kosong', 'https://www.tiket.com/promo/sewa-mobil/sewa-mobil-hemat', NULL, NULL, '', 'akomodasi', '', '', 'car', ''),
(8699, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/29/60d05807-9981-4a66-a067-91e4d8dd054a-1659062323219-5f4ef7c80cb1a99f7a2d911a4499835a.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/teman-baru', NULL, NULL, '', '', '', '', '', ''),
(8700, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/02/5f0efa30-9726-4836-8267-f70ed5f4a987-1659441275170-5638d2182e10227a2b537b634c37e3b0.png', '', 'kosong', 'https://www.tiket.com/promo/pesawat/lion-group', NULL, NULL, '', 'flight', '', '', '', ''),
(8701, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2021/10/22/91cf067a-58e1-419e-af8c-a02ec77495c6-1634879704945-07e88aac2de2314f4a67a62396f8584f.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/gv-bca', NULL, NULL, '', '', '', '', '', ''),
(8702, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/26/0179f4e6-8896-4ba7-a180-0026934e8552-1658803553355-ea5275a9c26c69bf0cd52f82237e9855.png', '', 'kosong', 'https://www.tiket.com/promo/pesawat/domestik-gopay', NULL, NULL, '', 'flight', '', '', '', ''),
(8703, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/19/739d5cea-9bec-4b36-9801-f8feadb83bce-1658216198281-8f9d4a08f3ea7b60732b120beb1e95a1.png', '', 'kosong', 'https://www.tiket.com/promo/hotel/hotel-gopay', NULL, NULL, '', 'hotel', '', '', '', ''),
(8704, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/02/5a7db506-8112-40ec-a43d-3e770c882644-1659410796427-0d371d6fd65b63d6ff7913c2a613098e.png', '', 'kosong', 'https://www.tiket.com/promo/pesawat/gopay', NULL, NULL, '', 'flight', '', '', '', ''),
(8705, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/29/e27080a5-ad6b-46aa-9f39-91edb11980ed-1659094686928-c60ddb3111ae3044ced24ba9af5d5d61.png', '', 'kosong', 'https://www.tiket.com/promo/pesawat/domestik-paylater', NULL, NULL, '', 'flight', '', '', '', ''),
(8706, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/26/0e0716e9-22ec-4be2-84dc-d6050427b6ca-1658803444121-b04bf99fa5c5a09e022ab0470ceffdd4.png', '', 'kosong', 'https://www.tiket.com/promo/kereta-api/gopay-kereta', NULL, NULL, '', 'akomodasi', '', '', 'train', ''),
(8707, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/21/a18a6d5e-1e9b-4fb1-a82f-139484a2c10c-1658375785104-840811de3bb30bda916b9965c4eccae4.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/event-paylater', NULL, NULL, '', '', '', '', '', ''),
(8708, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/11/c547020c-9895-45b5-92b8-36942097b715-1660183646837-2772cebbc2a129b1dd708cee0be0d839.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/tiket-sewa-mobil-airport-transfer', NULL, NULL, '', '', '', '', '', ''),
(8709, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/27/d48530ca-9ed8-4ab6-bfa7-8a5c8fdf102a-1658896073075-3b2d8f044b188b77bfd846792ec03ddf.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/promo-bni', NULL, NULL, '', '', '', '', '', ''),
(8710, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/07/26/c190f219-46d4-426f-858c-c28f030a7cf3-1658803242652-e43a1df77e282dbb7125af94be4a643d.png', '', 'kosong', 'https://www.tiket.com/promo/campaign/promo-uob', NULL, NULL, '', '', '', '', '', ''),
(8711, 2, 'kosong', 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfill19296gsm/promo/2022/08/02/4c2d82e0-b9f6-4651-a04d-84f6cc42bd5f-1659407269540-800060a75185c87635dc28883226fd21.png', '', 'kosong', 'https://www.tiket.com/promo/to-do/marvel-exhibition', NULL, NULL, '', '', '', '', '', ''),
(8712, 4, '\n        Stay Happy Weekly Bersama OCBC NISP, Dapatkan Diskon 12%\n      ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSCJcmW8o--f8RjjBGP964tWN6NY9RBw4ww&usqp=CAU', '2022-12-31', '\n            WEEKLYHO\n          ', 'https://www.airpaz.com/id/promo/view/OCBCWeeklyHotel', NULL, NULL, '', 'hotel', '12%', '2022-02-01', '', ''),
(8713, 4, '\n        Victorious Tuesday Bersama OCBC NISP, Dapatkan Diskon 12%\n      ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSCJcmW8o--f8RjjBGP964tWN6NY9RBw4ww&usqp=CAU', '2022-12-31', '\n            WEEKLYFL\n          ', 'https://www.airpaz.com/id/promo/view/OCBCWeeklyFlight', NULL, NULL, '', 'flight', '12%', '2022-02-01', '', ''),
(8714, 4, '\n        Puas Menginap Dengan Kartu Kredit Maybank Promo hingga IDR 200.000\n      ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSCJcmW8o--f8RjjBGP964tWN6NY9RBw4ww&usqp=CAU', '2022-12-31', '\n            MAYBANKHO200\n          ', 'https://www.airpaz.com/id/promo/view/maybank-hotel-reguler', NULL, NULL, '', 'hotel', '10%', '2022-06-15', '', ''),
(8715, 4, '\n        Penerbangan Jadi Menyenangkan Dengan Kartu Kredit Maybank Promo hingga IDR 200.000\n      ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSCJcmW8o--f8RjjBGP964tWN6NY9RBw4ww&usqp=CAU', '2022-12-31', '\n            MAYBANKFL200\n          ', 'https://www.airpaz.com/id/promo/view/maybank-flight-reguler', NULL, NULL, '', 'flight', ' 5%', '2022-06-15', '', ''),
(8716, 4, '\n        Aplikasi Super untuk Liburan Sempurna\n      ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSCJcmW8o--f8RjjBGP964tWN6NY9RBw4ww&usqp=CAU', '2022-08-15', '\n            APPFLIGHTIDR10\n          ', 'https://www.airpaz.com/id/promo/view/app-discount-id', NULL, NULL, '', 'lainnya', '', '2022-06-15', '', ''),
(8717, 4, '\n        Keuntungan OCBC NISP PayDay\n      ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSCJcmW8o--f8RjjBGP964tWN6NY9RBw4ww&usqp=CAU', '2022-12-31', '\n            PAYDAYHO\n          ', 'https://www.airpaz.com/id/promo/view/ocbc-hotel-payday', NULL, NULL, '', 'hotel', '15%', '2022-07-01', '', ''),
(8718, 4, '\n        Keuntungan OCBC NISP PayDay\n      ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSCJcmW8o--f8RjjBGP964tWN6NY9RBw4ww&usqp=CAU', '2022-12-31', '\n            PAYDAYFL\n          ', 'https://www.airpaz.com/id/promo/view/ocbc-flight-payday', NULL, NULL, '', 'flight', '15%', '2022-07-01', '', ''),
(8719, 4, '\n        Promo Hotel Hingga IDR 250K dengan OCBC\n      ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSCJcmW8o--f8RjjBGP964tWN6NY9RBw4ww&usqp=CAU', '2022-09-25', '\n            OCBCAHO\n          ', 'https://www.airpaz.com/id/promo/view/ocbc-hotel', NULL, NULL, '', 'hotel', 'i.000', '2022-07-25', '', ''),
(8720, 4, '\n        Promo Penerbangan Hingga IDR 350K dengan OCBC\n      ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSCJcmW8o--f8RjjBGP964tWN6NY9RBw4ww&usqp=CAU', '2022-09-25', '\n            OCBCSFL\n          ', 'https://www.airpaz.com/id/promo/view/ocbc-flight', NULL, NULL, '', 'flight', 'i.000', '2022-07-25', '', ''),
(8721, 4, '\n        Kumpul Indodana Points dengan Booking Kemerdekaan\n      ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSCJcmW8o--f8RjjBGP964tWN6NY9RBw4ww&usqp=CAU', '2022-08-31', 'Tidak memiliki', 'https://www.airpaz.com/id/promo/view/indodana-independence', NULL, NULL, '', 'lainnya', 'a.000', ' ', '', ''),
(8722, 4, '\n        Beli Sekarang dan Bayar Nanti dengan Atome\n      ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSCJcmW8o--f8RjjBGP964tWN6NY9RBw4ww&usqp=CAU', '2022-08-31', '\n            ATOME15ID\n          ', 'https://www.airpaz.com/id/promo/view/atome-id', NULL, NULL, '', 'lainnya', 'o.000', ' ', '', ''),
(8723, 4, '\n        Promo hingga [IDR 500K] dengan Nyala OCBC NISP\n      ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSCJcmW8o--f8RjjBGP964tWN6NY9RBw4ww&usqp=CAU', '2022-12-31', 'Tidak memiliki', 'https://www.airpaz.com/id/promo/view/nyala-ocbc', NULL, NULL, '', 'lainnya', ' .000', ' ', '', ''),
(8724, 4, '\n        Kesepakatan yang Adil Setiap Hari!\n      ', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSCJcmW8o--f8RjjBGP964tWN6NY9RBw4ww&usqp=CAU', '2022-08-31', '\n            APZFLIGHTIDR10\n          ', 'https://www.airpaz.com/id/promo/view/flight-discount-id', NULL, NULL, '', 'flight', '', ' ', '', ''),
(8725, 7, '         Citilink x Trevo   ', 'https://www.citilink.co.id/images/default-source/default-album/ctl-x-apps-trevo-landing-page.jpg?sfvrsn=0', NULL, ' Hanya berlaku untuk bookingan pertama Harga Rp.149.000 1 x 24 Jam, berlaku untuk 1 (satu) kali pemakaian & tidak berlaku kelipatan Promo berlaku dengan ketentuan potongan maksimal sebesar Rp.300.000,- Promo hanya berlaku untuk transaksi di aplikasi TREVO Promo tidak dapat digabung dengan promo lain yang ada di aplikasi TREVO Promo tidak dapat ditukar & diuangkan TREVO selaku penyelenggara promo dapat merubah skema promo sewaktu-waktu Info lebih lanjut dapat menghubungi TREVO di help@trevo.id ', 'https://www.citilink.co.id/citilink-trevo/?utm_source=Events_%26_Promos&utm_medium=Promo_Banner&utm_campaign=Trevo', NULL, NULL, '', 'lainnya', NULL, NULL, NULL, NULL),
(8726, 7, '         Citilink x digibank   ', 'https://www.citilink.co.id/images/default-source/default-album/dbs001.jpg?sfvrsn=0', NULL, ' Berlaku 30 hari sejak E-voucher Citilink dikirimkan Penggunaan E-voucher Citilink dengan minimum pembelanjaan senilai Rp1.000.000 E-voucher Citilink hanya dapat digunakan dengan pembayaran menggunakan Kartu Kredit Digital digibank yang diterbitkan di Indonesia dengan BIN (405549, 422143, 458769, 541616) ', 'https://www.citilink.co.id/bayar-pakai-digibank/?utm_source=Events_%26_Promos&utm_medium=Promo_Banner&utm_campaign=digibank', NULL, NULL, 'Indonesia', 'lainnya', NULL, NULL, NULL, NULL),
(8727, 7, '         Flexy Flight   ', 'https://www.citilink.co.id/images/default-source/default-album/flexy-flight-landing-page.jpg?sfvrsn=0', NULL, ' Berlaku untuk pembelian di member.citilink.co.id dan BetterFly Citilink mobile app Diskon berlaku untuk tiket penerbangan dengan kelas tertentu Perubahan jadwal dapat dilakukan maksimal 48 jam setelah penerbangan Bebas melakukan perubahan jadwal untuk tiket dengan kelas penerbangan A/ B/ D/ E Perubahan jadwal untuk tiket dengan kelas penerbangan selain A/ B/ D/ E dapat dilakukan 1 (satu) kali Diskon pembelian makanan Pre-Book Meals (PBM) dan kursi GreenZone sebesar 20% Promo tidak dapat digabungkan dengan promo lain Citilink berhak mengubah syarat dan ketentuan sewaktu-waktu tanpa pemberitahuan terlebih dahulu ', 'https://www.citilink.co.id/flexy-flight', NULL, NULL, '', 'flight', NULL, NULL, NULL, NULL),
(8728, 7, '         Family Pack   ', 'https://www.citilink.co.id/images/default-source/default-album/ctl-family-pack-landing-page.jpg?sfvrsn=0', NULL, ' Diskon tiket hingga 20% atau Cashback LinkPoint untuk class promo Diskon tiket tidak berlaku untuk class promo Diskon tiket tambahan 5% untuk penumpang anak-anak Ekstra bagasi sebesar 5 (lima) kilogram Bonus 1000 miles untuk member baru ', 'https://www.citilink.co.id/new-family-pack/', NULL, NULL, '', 'lainnya', NULL, NULL, NULL, NULL),
(8729, 7, '             Bayar Pakai Kredivo Refund Voucher   ', 'https://www.citilink.co.id/images/default-source/default-album/ctl-x-kredivo-cicilan-0--landing-page.jpg?sfvrsn=0', NULL, ' Pilih Kredivo saat pembayaran dan login ke akun Kredivo-mu Pilih tenor cicilan 6 bulan Klik \"Voucher belanja hemat\" dan pilih voucher Promo Cicilan 0% Promo cicilan akan langsung ter-apply di transaksimu! ', 'https://www.citilink.co.id/bayar-pakai-kredivo/?utm_source=Events_%26_Promos&utm_medium=Promo_Banner&utm_campaign=kredivo', NULL, NULL, '', 'flight', NULL, NULL, NULL, NULL),
(8730, 7, '         LinkMiles   ', 'https://www.citilink.co.id/images/default-source/default-album/ctl-join-linkmiles-landing-page.jpg?sfvrsn=0', NULL, 'Go to detail link promo', 'https://www.citilink.co.id/linkmiles/', NULL, NULL, '', 'lainnya', NULL, NULL, NULL, NULL),
(8731, 7, '          Citilink Store di Tokopedia   ', 'https://www.citilink.co.id/images/default-source/default-album/ctl5-citilink-tokopedia-landing-page.jpg?sfvrsn=2', NULL, 'Go to detail link promo', 'https://www.citilink.co.id/official-store-citilink-di-tokopedia/', NULL, NULL, '', 'lainnya', NULL, NULL, NULL, NULL),
(8732, 7, '         Moodday   ', 'https://www.citilink.co.id/images/default-source/default-album/monday1.jpg?sfvrsn=0', NULL, ' Masuk ke aplikasi Citilink Lakukan pemesanan tiket pesawat ke destinasi yang kamu inginkan Pastikan kamu melakukan pemesanan tiket di hari Senin Selesaikan pembayaran dengan menggunakan Kartu Kredit Citibank Diskon akan secara otomatis didapat pada akhir pembayaran ', 'https://www.citilink.co.id/moodday-citi/', NULL, NULL, '', 'lainnya', NULL, NULL, NULL, NULL),
(8733, 7, '         Toursday   ', 'https://www.citilink.co.id/images/default-source/default-album/toursday_1.jpg?sfvrsn=0', NULL, ' Masuk ke aplikasi BetterFly Citilink Lakukan pemesanan tiket pesawat ke destinasi yang kamu inginkan Pastikan kamu melakukan pemesanan tiket di hari Selasa Selesaikan pembayaran dengan menggunakan Kartu Kredit CIMB Niaga Diskon akan secara otomatis didapat pada akhir pembayaran ', 'https://www.citilink.co.id/toursday-cimb/', NULL, NULL, '', 'flight', NULL, NULL, NULL, NULL),
(8734, 7, '         Thursday Treat   ', 'https://www.citilink.co.id/images/default-source/default-album/thurs1.jpg?sfvrsn=0', NULL, ' Masuk ke aplikasi Citilink Lakukan pemesanan tiket pesawat ke destinasi yang kamu inginkan Pastikan kamu melakukan pemesanan tiket di hari Kamis Selesaikan pembayaran dengan menggunakan Kartu Debit BNI Diskon akan secara otomatis didapat pada akhir pembayaran ', 'https://www.citilink.co.id/thursday-treat-bni', NULL, NULL, '', 'lainnya', NULL, NULL, NULL, NULL),
(8735, 7, '         Flyday   ', 'https://www.citilink.co.id/images/default-source/default-album/friday1.jpg?sfvrsn=0', NULL, ' Masuk ke aplikasi BetterFly Citilink Lakukan pemesanan tiket pesawat ke destinasi yang kamu inginkan Pastikan kamu melakukan pemesanan tiket di hari Jumat Selesaikan pembayaran dengan menggunakan Kartu Kredit / Kartu Debit Bank Mega Diskon akan secara otomatis didapat pada akhir pembayaran ', 'https://www.citilink.co.id/flyday-mega', NULL, NULL, '', 'flight', NULL, NULL, NULL, NULL),
(8736, 7, '         Saleturday   ', 'https://www.citilink.co.id/images/default-source/default-album/saturday1.jpg?sfvrsn=0', NULL, ' Masuk ke aplikasi BetterFly Citilink Lakukan pemesanan tiket pesawat ke destinasi yang kamu inginkan Pastikan kamu melakukan pemesanan tiket di hari Sabtu Selesaikan pembayaran dengan menggunakan Kartu Kredit Bank Mandiri Diskon akan secara otomatis didapat pada akhir pembayaran ', 'https://www.citilink.co.id/saletourday-mandiri/', NULL, NULL, '', 'flight', NULL, NULL, NULL, NULL),
(8737, 7, '         Menu Pre Book Meals   ', 'https://www.citilink.co.id/images/default-source/default-album/pre-book-meals-landing-page.jpg?sfvrsn=0', NULL, ' Pemesanan melalui Pre-Book Meals (PBM) dapat dilayani selambat-lambatnya 24 jam sebelum jam penerbangan,bersamaan dengan pemesanan tiket. Jenis PBM yang dipesan akan tercantum pada boarding pass customer dan dapat di klaim ke awak cabin kami selama melakukan penerbangan, sesuai dengan rute keberangkatan dari bandar udara CGK,SUB dan DPS. Pesanan yang telah dilakukan dapat ditukar dengan menu lain yang senilai, apabila pesanan tersebut mengalami kerusakan atau hal lain yang menyebabkan pesanan tidak layak di konsumsi Makanan yang dipesan tidak dapat dibatalkan, dipindah tangankan, ataupun ditukar setelah melakukan pemesanan. Segala sesuatu/keadaan kahar (force majeure) di luar kemampuan PT. Citilink Indonesia, yang menyebabkan makanan tidak diterima  oleh penumpang, maka Citilink tidak berkewajiban atas penggantian tersebut.  Penggantian biaya order PBM akan dikembalikan, apabila terjadi pembatalan sepihak penerbangan oleh pihak Citilink Pembatalan pesanan tidak dapat dilakukan, apabila terjadi perubahan jadwal atas permintaan penumpang (re-schedule atau pax no show). ', 'https://www.citilink.co.id/menu-pre-book-meals', NULL, NULL, 'surabaya', 'lainnya', NULL, NULL, NULL, NULL),
(8738, 7, '         DailyBox   ', 'https://www.citilink.co.id/images/default-source/default-album/kv-inflight-dailybox-landing-page-(1).jpg?sfvrsn=0', NULL, ' Pemesanan melalui Pre-Book Meals (PBM) dapat dilayani selambat-lambatnya 24 jam sebelum jam penerbangan,bersamaan dengan pemesanan tiket. Jenis PBM yang dipesan akan tercantum pada boarding pass customer dan dapat di klaim ke awak kabin kami selama melakukan penerbangan, sesuai dengan rute keberangkatan dari bandar udara CGK. Pesanan yang telah dilakukan dapat ditukar dengan menu lain yang senilai, apabila pesanan tersebut mengalami kerusakan atau hal lain yang menyebabkan pesanan tidak layak di konsumsi. Makanan yang dipesan tidak dapat dibatalkan, dipindah tangankan, ataupun ditukar setelah melakukan pemesanan. Segala sesuatu/keadaan kahar (force majeure) diluar kemampuan PT. Citilink Indonesia, yang menyebabkan makanan tidak diterima oleh penumpang, maka Citilink tidak berkewajiban atas penggantian tersebut.  Penggantian biaya order PBM akan dikembalikan, apabila terjadi pembatalan sepihak penerbangan oleh pihak Citilink Pembatalan pesanan tidak dapat dilakukan, apabila terjadi perubahan jadwal atas permintaan penumpang (re-schedule atau pax no show). ', 'https://www.citilink.co.id/citilink-x-dailybox/', NULL, NULL, 'jakarta', 'lainnya', NULL, NULL, NULL, NULL),
(8739, 7, '         Group Booking Citilink   ', 'https://www.citilink.co.id/images/default-source/default-album/group-booking-banner-ind1.jpg?sfvrsn=2', NULL, 'Go to detail link promo', 'https://groupbook.citilink.co.id/#/', NULL, NULL, '', 'lainnya', NULL, NULL, NULL, NULL),
(8740, 7, '         Citilink Lounge   ', 'https://www.citilink.co.id/images/default-source/default-album/ctl-saphire-update-landing-page1acbe57eddd767d084cdff0000433061.jpg?sfvrsn=0', NULL, ' Penumpang dapat melakukan pembelian produk Garuda Indonesia Executive Lounge secara langsung di kasir ataupun pre – book melalui website www.citilink.co.id ataupun mobile apps BettertFly Citilink seharga:\n     Bandar Udara Internasional Soekarno-Hatta – Tangerang, Terminal 3 Domestik (Rp. 250.000 including tax) Bandar Udara Internasional I Gusti Ngurah Rai – Denpasar, Terminal Domestik (Rp. 250.000 including tax)   Penumpang yang membeli produk pre – book lounge melalui website www.citilink.co.id ataupun mobile apps BettertFly Citilink wajib menunjukkan kembali boarding pass atau e-ticket yang terdapat kode SSR LGA kepada staff Garuda Executive Lounge. Layanan Garuda Executive Lounge belum berlaku sebagai fasilitas bagi penumpang Citilink pemegang Garuda Miles Platinum / Elite Plus / Gold / Elite. Penumpang berhak mendapatkan layanan fasilitas berupa finger foods, minuman, smoking area, musholla, toilet, TV cable, Free Wifi dan ruang tunggu yang lebih nyaman (Fasilitas dan layanan mengacu kepada standar SOP yang berlaku di Garuda Indonesia Executive Lounge) Bagi penumpang yang membeli lounge secara langsung di kasir / ticketing maka dapat menunjukkan bukti pembayaran untuk dapat memasuki Garuda Executive Lounge. Bukti pembayaran PRL (Payment Receipt Lounge) berlaku digunakan pada tanggal yang sama dengan jadwal pembayaran. Penumpang dapat mengakses Garuda Executive Lounge dalam waktu 4 jam sebelum jadwal penerbangan keberangkatan. Akses Lounge bergantung pada ketersediaan lounge aktual, dan tidak akan tersedia pada Tanggal Black Out Date, seperti:\n     7 hari sebelum dan sesudah Tahun Baru Periode peak season (liburan sekolah, akhir pekan yang panjang (long weekend), dll) Kebijakan black out date mengacu kepada SOP yang berlaku pada Garuda Indonesia Executive Lounge   Tidak ada biaya untuk bayi di bawah 24 bulan bepergian dengan orang dewasa yang memiliki PRL Akses Lounge Prabayar. Tidak ada pembelian maksimum untuk pemesanan individu. Bagi penumpang yang membeli produk Green Zone ataupun Green Premium harus melakukan pembelian akses Garuda Executive Lounge secara terpisah. Akses Lounge yang sudah di beli tidak dapat dibatalkan, ditransfer ke penumpang lain, ditukar, atau dikembalikan setelah pembelian. (Full refund hanya berlaku bagi penumpang yang sudah melakukan pembelian pre – book lounge namun tetapi lounge di bandara keberangkatan tutup di karenakan alasan operasional) ', 'https://www.citilink.co.id/citilink-lounge/', NULL, NULL, 'Kenya', 'lainnya', NULL, NULL, NULL, NULL),
(8741, 7, '             Promo - Alfamart Promo - Indomaret    ', 'https://www.citilink.co.id/images/default-source/default-album/ctl-alfamart-voucher-kemerdekaan-landing-page.jpg?sfvrsn=0', NULL, 'Go to detail link promo', 'https://www.citilink.co.id/promo---alfamart/?utm_source=Event-Promo&utm_medium=CTA&utm_campaign=Alfamart', NULL, NULL, 'Tonga', 'flight', NULL, NULL, NULL, NULL),
(8742, 5, 'Nusatrip\'s Flights Fest, Gratis, Diskon dan Cashback Tiket Pesawat. Pesan: s.d. 8 Mar 2020 | Terbang: s.d. 16 Des 2020', 'https://sta.nusatrip.net/cmsimg/50/350/td-nff-02-20_id.jpg', '2020-03-08', '\n\n\n\n\n\n\nPeriode Promo berlaku mulai 24 Februari – 8 Maret, 2020\n\n\n\n\n\n\n\nHanya berlaku untuk pemesanan yang dimulai dari URL berikut: nusatrip.com/flightsfest\n\n\n\n\n\n\n\nReservasi tiket pesawat apapun (1xjalan/pergi-pulang) dan/atau hotel di Indonesia dan seluruh dunia dengan minimum transaksi IDR 1.000.000\n\n\n\n\n\n\n\nPemesanan Tiket Pesawat dan/ Hotel dalam promo ini tidak bisa dibatalkan (non-refundable)\n\n\n\n\n\n\n\nPembeli harus ikut terbang bersama dan atau merupakan tamu hotel yang menginap\n\n\n\n', 'https://www.nusatrip.com/id/promo/festival-penerbangan-harga-tiket-pesawat-murah-februari-maret-2020', NULL, NULL, '', 'flight', '', NULL, NULL, NULL),
(8743, 5, 'Philippine Airlines promo tiket pesawat murah mulai dari IDR 1.2 jt PP. Pesan: s.d. 15 Mar 2020 | Terbang: s.d. 10 Des 2020', 'https://sta.nusatrip.net/cmsimg/50/350/tda-pr-02-20_id.jpg', '2020-03-15', 'Jalan-jalan ke Manila, Tokyo, Los Angeles atau destinasi favorit lainnya di Asia & Amerika dengan terbang murah bersama Philippine Airlines mulai dari IDR 1.2 jt* harga total PP hanya di NusaTrip.com\nAyo, pesan sekarang sebelum kehabisan kursi!\n', 'https://www.nusatrip.com/id/promo/philippine-airlines-tiket-pesawat-murah-februari-maret-2020', NULL, NULL, '', 'flight', '1.200.000', NULL, NULL, NULL),
(8744, 5, 'Nikmati cashback s.d IDR 1.125 Jt untuk hotel di seluruh dunia & tiket pesawat. Pesan: s.d. 31 May 2020', 'https://sta.nusatrip.net/cmsimg/50/350/tdb-citi-02-20.jpg', '2020-05-31', '\n\n\n\n•\n\n\nBerlaku untuk semua pemegang Kartu Kredit Citibank kecuali corporate card\n\n\n\n\n•\n\n\nHanya berlaku untuk pemesanan dari URL berikut: nusatrip.com/citibank dari 1 Maret – 31 Mei 2020\n\n\n\n\n•\n\n\nCashback hanya berlaku 1x transaksi per hari per pemegang kartu per produk (hotel dan/atau tiket pesawat) selama periode promosi\n\n\n\n\n•\n\n\nPemesanan hotel dan/atau tiket pesawat dalam promo ini tidak bisa dibatalkan (non refundable)\n\n\n\n\n•\n\n\nPromosi ini tidak bisa digabungkan dengan promosi lain\n\n\n\n\n•\n\n\nNusaTrip berhak untuk mengubah dan/atau memodifikasi syarat & ketentuan promosi ini dengan atau tanpa pemberitahuan terlebih dahulu\n\n\n\n\n•\n\n\nNusaTrip berhak untuk menolak klaim cashback untuk transaksi yang tidak memenuhi syarat & ketentuan yang berlaku\n\n\n\n\n•\n\n\nDengan mengikuti promosi ini, customer dianggap telah mengetahui & menyetujui syarat & ketentuan yang berlaku\n\n\n\n\n•\n\n\nJika terjadi perbedaan penafsiran dalam syarat & ketentuan program ini maka yang dianggap benar adalah keputusan NusaTrip.com\n\n\n\n', 'https://www.nusatrip.com/id/promo/citibank-kartu-kredit-cashback-tiket-pesawat-hotel-murah-mar-mei-2020', NULL, NULL, '', 'flight hotel', '1.125.000', NULL, NULL, NULL),
(8745, 5, 'Dapatkan cashback s.d IDR 1.1 Jt untuk hotel di seluruh dunia & tiket pesawat. menangkan 2 Tiket PP Jakarta – Yogyakarta. Pesan: s.d. 31 May 2020', 'https://sta.nusatrip.net/cmsimg/50/350/tdb-ocbc-02-20.jpg', '2020-05-31', '\n\n\n\n•\n\n\nCashback hanya berlaku untuk kartu Debit & Kartu Kredit OCBC NISP (kecuali kartu korporasi)\n\n\n\n\n•\n\n\nHanya berlaku untuk pemesanan dari URL berikut: nusatrip.com/ocbcnisp periode hingga 31 Mei 2020\n\n\n\n\n•\n\n\nCashback hanya berlaku 1x transaksi per hari per pemegang kartu per produk (tiket pesawat dan/atau hotel) selama periode promosi\n\n\n\n\n•\n\n\nPemesanan tiket pesawat dan/atau hotel dalam promo ini tidak bisa dibatalkan (non refundable)\n\n\n\n\n•\n\n\nPromosi ini tidak bisa digabungkan dengan promosi lain\n\n\n\n\n•\n\n\nNusaTrip berhak untuk mengubah dan/atau memodifikasi syarat & ketentuan promosi ini dengan atau tanpa pemberitahuan terlebih dahulu\n\n\n\n\n•\n\n\nNusaTrip berhak untuk menolak klaim cashback untuk transaksi yang tidak memenuhi syarat & ketentuan\n\n\n\n\n•\n\n\nDengan mengikuti promosi ini, customer dianggap telah mengetahui & menyetujui syarat & ketentuan yang berlaku\n\n\n\n\n•\n\n\nJika terjadi perbedaan penafsiran dalam syarat & ketentuan program ini maka yang dianggap benar adalah keputusan NusaTrip.com\n\n\n\n', 'https://www.nusatrip.com/id/promo/travel-bank-ocbc-nisp-kartu-kredit-cash-back-tiket-pesawat-hotel-murah-mar-mei-2020', NULL, NULL, 'jakarta', 'flight hotel', '', NULL, NULL, NULL),
(8746, 5, 'Nikmati cashback s.d IDR 1.050 Jt untuk hotel di seluruh dunia & tiket pesawat. menangkan 2 Tiket Pesawat PP. Pesan: s.d. 31 May 2020', 'https://sta.nusatrip.net/cmsimg/50/350/tdb-uob-02-20.jpg', '2020-05-31', '\n\n\n\n•\n\n\nBerlaku untuk pemegang kartu kredit UOB\n\n\n\n\n•\n\n\nHanya berlaku untuk pemesanan dari URL berikut: nusatrip.com/uob hingga 31 Mei 2020\n\n\n\n\n•\n\n\nCashback hanya berlaku 1x transaksi per hari per pemegang kartu per produk (tiket pesawat dan/atau hotel) selama periode promosi\n\n\n\n\n•\n\n\nPemesanan tiket pesawat dan/atau hotel dalam promo ini tidak bisa dibatalkan (non-refundable)\n\n\n\n\n•\n\n\nPromosi ini tidak bisa digabungkan dengan promosi lain\n\n\n\n\n•\n\n\nNusaTrip berhak untuk mengubah dan/atau memodifikasi syarat & ketentuan promosi ini dengan atau tanpa pemberitahuan terlebih dahulu\n\n\n\n\n•\n\n\nNusaTrip berhak untuk menolak klaim cashback untuk transaksi yang tidak memenuhi syarat & ketentuan\n\n\n\n\n•\n\n\nDengan mengikuti promosi ini, customer dianggap telah mengetahui & menyetujui syarat & ketentuan yang berlaku\n\n\n\n\n•\n\n\nJika terjadi perbedaan penafsiran dalam syarat & ketentuan program ini maka yang dianggap benar adalah keputusan NusaTrip.com\n\n\n\n', 'https://www.nusatrip.com/id/promo/kartu-kredit-uob-indonesia-extra-cash-back-cicilan-tiket-pesawat-hotel-murah-mar-mei-2020', NULL, NULL, '', 'flight hotel', '1.050.000', NULL, NULL, NULL),
(8747, 6, '\nHemat Setiap Hari dengan UOB!\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-promo-uob-april-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/UOB-daily-deals', NULL, NULL, '', NULL, '', NULL, NULL, NULL);
INSERT INTO `promo` (`id`, `id_website`, `name`, `img`, `end_date`, `description`, `link`, `created_at`, `updated_at`, `location`, `category`, `discount`, `start_date`, `maskapai`, `lokasi_hotel`) VALUES
(8748, 6, '\nSetiap hari hemat hingga Rp500.000 dengan TMRW by UOB!\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-tmrw-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/tmrw-uob', NULL, NULL, 'Tonga', NULL, '500.000', NULL, NULL, NULL),
(8749, 6, '\nPotongan s.d Rp500.000 dari Maybank Setiap Senin!\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-maybank-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/maybank-monday-deals', NULL, NULL, 'Tonga', NULL, '500.000', NULL, NULL, NULL),
(8750, 6, 'Potongan spesial hingga Rp1.000.000 dari digibank!\nLebih Rinci\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/promo-dbs-juli2022-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/dbs-daily-deals', NULL, NULL, 'Tonga', NULL, '1.000.000', NULL, NULL, NULL),
(8751, 6, '\nTMRWPay hemat hingga Rp500.000!\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-tmrwpay-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/tmrwpay-daily-deal', NULL, NULL, '', NULL, '', NULL, NULL, NULL),
(8752, 6, '\nPotongan Tambahan hingga Rp250.000 dari Bank Mega!\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-promo-megadeals-april-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/Mega-Tuesday-deals', NULL, NULL, 'Tonga', NULL, '250.000', NULL, NULL, NULL),
(8753, 6, '\nKeuntungan lebih pembelian tiket Garuda Indonesia dengan OCBC NISP setiap Selasa!\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-ocbc-nisp-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/ocbc-nisp-tuesday-deals', NULL, NULL, 'Tonga', NULL, '300.000', NULL, NULL, NULL),
(8754, 6, '\nBNIWOW! POTONGAN TAMBAHAN HINGGA RP750RIBU SETIAP RABU\n\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/promo-bniwow-juli2022-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/bni-wow-wednesday-promo', NULL, NULL, 'Tonga', NULL, '/50.000', NULL, NULL, NULL),
(8755, 6, '\nCITI DEALS\n\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-citideals-update-june-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/citideals', NULL, NULL, 'Tonga', NULL, '600.000', NULL, NULL, NULL),
(8756, 6, '\nPOTONGAN HINGGA RP225.000 SETIAP JUMAT DAN SABTU DARI PERMATA BANK\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/promo-permata-juli2022-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/promo-permata-bank', NULL, NULL, 'Tonga', NULL, '', NULL, NULL, NULL),
(8757, 6, '\nCICILAN 0% DENGAN KARTU BANK ANDA\n\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-cicilan-0persen.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/cicilan-0-persen-dengan-kartu-bank-anda', NULL, NULL, '', NULL, '', NULL, NULL, NULL),
(8758, 6, '\nKREDIVO PROMO!\n\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-kredivo-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/kredivo.html', NULL, NULL, 'Indonesia', NULL, '', NULL, NULL, NULL),
(8759, 6, '\nBERIKAN HADIAH TERBAIK DENGAN GARUDA INDONESIA TRAVEL VOUCHER\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/travel-voucher-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/travel-voucher', NULL, NULL, 'Indonesia', NULL, '500.000', NULL, NULL, NULL),
(8760, 6, '\nKEUNTUNGAN LEBIH BAGI PERJALANAN BISNIS ANDA\n\n', 'https://www.garuda-indonesia.com/content/dam/garuda/penawaran/thumb-corporate-special-delas.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/corporate-special-deals', NULL, NULL, '', NULL, '', NULL, NULL, NULL),
(8761, 6, '\nBonus 30% GarudaMiles untuk penukaran Livin\' Poin Mandiri Kartu Kredit Event Livin’ Sukha\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-livin-sukha-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/GA-Livin-Sukha-Mandiri', NULL, NULL, 'Indonesia', NULL, '', NULL, NULL, NULL),
(8762, 6, '\nAjukan Kartu Kredit Garuda BNI Dapatkan Tambahan Bonus 25.000 Miles dan Cashback Rp 1.000.000\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-cobrand-bni-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/cobrand-GA-BNI', NULL, NULL, 'Indonesia', NULL, '1.000.000', NULL, NULL, NULL),
(8763, 6, '\nPundi Jenius\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-jenius-id.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/pundi-jenius', NULL, NULL, '', NULL, '', NULL, NULL, NULL),
(8764, 6, '\nDAPATKAN OFFICIAL MERCHANDISE MARVEL STUDIOS’ \"HAWKEYE\"\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-hawkeye.JPG', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n*Penukaran miles GarudaMiles tidak berlaku untuk penerbangan Citilink\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Booking.com\nKini Anda dapat merencanakan perjalanan Anda tanpa hambatan dengan memesan Kamar Hotel bersama kami. Kami telah bermitra dengan Booking.com salah satu situs pencarian akomodasi terbesar di dunia. Anda dapat memilih lebih dari 28 juta akomodasi yang terdaftar, termasuk lebih dari 6,2 juta rumah, apartemen, dan tempat menginap unik lainnya. Klik pada link dibawah untuk menikmati penawaran ini.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/id/id/special-offers/sales-promotion/dapatkan-merchandise-marvel-studios-hawkeye', NULL, NULL, '', NULL, '', NULL, NULL, NULL),
(8765, 6, '\nTUKARKAN MILES DAN DAPATKAN VOUCHER KirimAja HINGGA IDR 100,000 UNTUK KEMUDAHAN PENGIRIMAN PAKET ANDA\n', 'https://www.garuda-indonesia.com/content/dam/garuda/garudamiles/thumb-kirimaja.png', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Hotelopia\nKami menawarkan penawaran terbaik yang memungkinkan anda untuk memilih hotel dan juga mempunyai peluang untuk memilih akomodasi di seluruh dunia - Pemesanan online yang selamat dan 250,000 ulasan dari para pelancong. Klik pada link di bawah ini untuk menikmati!\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/garudamiles/id/penukaran-miles/lifestyle/voucher-kirim-aja', NULL, NULL, '', NULL, '', NULL, NULL, NULL),
(8766, 6, '\nKUMPULKAN GARUDAMILES LEBIH BANYAK DENGAN MENUKARKAN CHOPE-DOLLARS \n', 'https://www.garuda-indonesia.com/content/dam/garuda/garudamiles/thumb-chope.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Hotelopia\nKami menawarkan penawaran terbaik yang memungkinkan anda untuk memilih hotel dan juga mempunyai peluang untuk memilih akomodasi di seluruh dunia - Pemesanan online yang selamat dan 250,000 ulasan dari para pelancong. Klik pada link di bawah ini untuk menikmati!\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/garudamiles/id/perolehan-miles/lifestyle/chope', NULL, NULL, '', NULL, '', NULL, NULL, NULL),
(8767, 6, '\nKini Anda Bisa Menikmati Fasilitas FINNS BALI dengan Harga Special, Hanya dengan Menukarkan GarudaMiles\n', 'https://www.garuda-indonesia.com/content/dam/garuda/garudamiles/thumb-finns-bali.png', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Hotelopia\nKami menawarkan penawaran terbaik yang memungkinkan anda untuk memilih hotel dan juga mempunyai peluang untuk memilih akomodasi di seluruh dunia - Pemesanan online yang selamat dan 250,000 ulasan dari para pelancong. Klik pada link di bawah ini untuk menikmati!\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/garudamiles/id/penukaran-miles/lifestyle/finns-bali', NULL, NULL, 'bali', NULL, '', NULL, NULL, NULL),
(8768, 6, '\nTukarkan Miles Anda dan Dapatkan Voucher discount CHOPE sampai dengan IDR 750.000 untuk Menikmati Berbagai Restoran di Jakarta & Bali\n', 'https://www.garuda-indonesia.com/content/dam/garuda/garudamiles/thumb-chope.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Hotelopia\nKami menawarkan penawaran terbaik yang memungkinkan anda untuk memilih hotel dan juga mempunyai peluang untuk memilih akomodasi di seluruh dunia - Pemesanan online yang selamat dan 250,000 ulasan dari para pelancong. Klik pada link di bawah ini untuk menikmati!\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/garudamiles/id/penukaran-miles/fnb/voucher-discount-chope', NULL, NULL, 'jakarta', NULL, '', NULL, NULL, NULL),
(8769, 6, '\nDapatkan Bonus Miles Hingga 80,000 Miles dengan Menukarkan Poin Bank Anda \n\n', 'https://www.garuda-indonesia.com/content/dam/garuda/garudamiles/news-and-offers/THUMBNAIL_Miles-Hunter-IND.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Hotelopia\nKami menawarkan penawaran terbaik yang memungkinkan anda untuk memilih hotel dan juga mempunyai peluang untuk memilih akomodasi di seluruh dunia - Pemesanan online yang selamat dan 250,000 ulasan dari para pelancong. Klik pada link di bawah ini untuk menikmati!\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/garudamiles/id/news-and-offers/news/the-miles-hunter', NULL, NULL, '', NULL, '', NULL, NULL, NULL),
(8770, 6, '\nDaftar Sekarang menjadi Nasabah Baru Bank BTN Prioritas dan Dapatkan Welcome Bonus Hingga 210.000 Miles + Cashback hingga 15 Juta Rupiah\n', 'https://www.garuda-indonesia.com/content/dam/garuda/offers/thumb-gamilesbtn-rev.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Hotelopia\nKami menawarkan penawaran terbaik yang memungkinkan anda untuk memilih hotel dan juga mempunyai peluang untuk memilih akomodasi di seluruh dunia - Pemesanan online yang selamat dan 250,000 ulasan dari para pelancong. Klik pada link di bawah ini untuk menikmati!\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/garudamiles/id/perolehan-miles/bank-BTN-prioritas', NULL, NULL, '', NULL, '', NULL, NULL, NULL),
(8771, 6, '\nAjukan Kartu Kredit GICC dan dapatkan 12.500 GarudaMiles + Cashback Rp 500.000,-\n', 'https://www.garuda-indonesia.com/content/dam/garuda/garudamiles/THUMBNAIL-GICC.jpg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Hotelopia\nKami menawarkan penawaran terbaik yang memungkinkan anda untuk memilih hotel dan juga mempunyai peluang untuk memilih akomodasi di seluruh dunia - Pemesanan online yang selamat dan 250,000 ulasan dari para pelancong. Klik pada link di bawah ini untuk menikmati!\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/content/garuda/garudamiles/id/news-and-offers/news/kartu-kredit-gicc', NULL, NULL, '', NULL, '', NULL, NULL, NULL),
(8772, 6, 'Tukar Miles untuk Voucher Diskon Belanja di GarudaShop\nLebih Rinci\n', 'https://www.garuda-indonesia.com/content/dam/garuda/garudamiles/thumb-garudashop-en.jpg', NULL, '\nx\n\n\n\nFlight\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nFrom\n\n\n\n\n\n\n\n\nTo \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nOne Way\n\n\n\nReturn\n\n\nMulticity\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nAdult (>11 years)\n\n\n\n\n\n\n\n\n\n\nChildren (2-11 years)?\n\n\n\n\n\n\n\n\n\n\nInfant (0-23 months)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nRedeem MilesSearch Flight\n\n*GarudaMiles redemption is not available for Citilink flights\n\n\n\n\nHotel\n\nBook a Hotel Room with Booking.com\nNow you can plan your trip seamlessly by booking your hotel with us. We\'ve partnered with Booking.com - the world\'s largest accommodation search site. You can choose from over 28 million listed accommodation listings, including more than 6.2 million listings of homes, apartments, and other unique places to stay. Click on the link below to enjoy this offer.\n\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/garudamiles/id/penukaran-miles/belanja/voucher-GARUDASHOP', NULL, NULL, '', NULL, '', NULL, NULL, NULL),
(8773, 6, '\nTukarkan Miles Anda menjadi Beragam Voucher Menarik\n', 'https://www.garuda-indonesia.com/content/dam/garuda/garudamiles/thumb-beragam-voucherrev2.jpeg', NULL, '\nx\n\n\n\nPenerbangan\n\n\nHotel\n\n\nCars\n\n\n\n\n\n\n\n\n\nDari\n\n\n\n\n\n\n\n\nKe\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSekali Jalan\n\n\n\nPergi Pulang\n\n\nBeberapa Kota\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDewasa (>11 tahun)\n\n\n\n\n\n\n\n\n\n\nAnak (2-11 tahun)?\n\n\n\n\n\n\n\n\n\n\nBayi (0-23 bulan)?\n\n\n\n\n.\n\n\n\n\n\n\nClass\n\n\nEconomy Class\nBusiness Class\nFirst Class\n\n\n\n\n\n\n?\n\n\n\n\n\n\n\n\n\n\n\n\n\nTukar MilesCari Penerbangan\n\n\n\n\n\n\nHotel\n\nPesan Kamar Hotel melalui Hotelopia\nKami menawarkan penawaran terbaik yang memungkinkan anda untuk memilih hotel dan juga mempunyai peluang untuk memilih akomodasi di seluruh dunia - Pemesanan online yang selamat dan 250,000 ulasan dari para pelancong. Klik pada link di bawah ini untuk menikmati!\n\nBook Hotel\n\n\n\n\n\n\n\n\n\n', 'https://www.garuda-indonesia.com/garudamiles/id/penukaran-miles/beragam-voucher', NULL, NULL, '', NULL, '', NULL, NULL, NULL),
(8774, 3, 'Discounts up to 70% for Various Traveloka Products!', 'https://ik.imagekit.io/tvlk/image/imageResource/2022/08/03/1659523632936-5c028cfba7d732faefec4eb88c603424.png', '2022-08-17', 'Celebrate life with #DuarDuarKemerdekaan only in your lifestyle superapp!', 'https://www.traveloka.com/en-id/promotion/merdeka-88', NULL, NULL, '', '', '70%', '2022-08-09', '', ''),
(8775, 3, '💥Duar Duar Merdeka 💥', 'https://ik.imagekit.io/tvlk/image/imageResource/2022/08/07/1659883093113-87e7e12169343c7c13530a47f8032302.jpeg', '2022-08-17', 'Been a while since your last me-time sesh or a vacation trip with your loved ones? Special on Indonesian Independence Day, you deserve to #LihatDuniaLagi with your trusted Teman Hidup!', 'https://www.traveloka.com/en-id/promotion/merdeka-hotel', NULL, NULL, '', 'hotel', '', '2022-08-09', '', ''),
(8776, 3, 'DUAR DUAR MERDEKA', 'https://ik.imagekit.io/tvlk/image/imageResource/2022/08/08/1659951243320-f74d65e1b52a07910e8933f671ea87c1.jpeg', '2022-08-17', 'Celebrate the Indonesian Independence Day with Duar Duar Merdeka promo!', 'https://www.traveloka.com/en-id/promotion/merdeka-intlhotel', NULL, NULL, '', 'hotel', '{0.000', '2022-08-09', '', ''),
(8777, 3, '💥Duar Duar Merdeka 💥', 'https://ik.imagekit.io/tvlk/image/imageResource/2022/08/05/1659683302412-4b3b7b27554bfc74565b35f384645303.jpeg', '', 'Something different from Traveloka to celebrate Independence Day! Enjoy Duar Duar Merdeka discounts up to Rp770,000 and extra discounts up to 30% off during 9-17 August 2022. Don\'t miss them discounts! Let’s #LihatDuniaLagi and have a staycation with Traveloka! Booking period: 9 - 17 August 2022 Check Traveloka App to get this promo', 'https://www.traveloka.com/en-id/promotion/merdeka-villa', NULL, NULL, '', '', '', '', '', ''),
(8778, 3, 'Flight Discount up to Rp1.7mio ✈️   ', 'https://ik.imagekit.io/tvlk/image/imageResource/2022/08/05/1659688978849-1448433217cd53e02ea4f5bc9b2f60a6.png', '', 'Only your lifestyle superapp that can give you #DuarDuarKemerdekaan promo on this celebrated time! ', 'https://www.traveloka.com/en-id/promotion/merdeka-flightdom', NULL, NULL, '', 'flight', '', '', '', ''),
(8779, 3, 'Car Rental discount of up to Rp77k + 30%', 'https://ik.imagekit.io/tvlk/image/imageResource/2022/08/04/1659598191263-756a6573f6d7d4df3c135774a94b3a06.jpeg', '', 'Independence day becomes more exciting with #MerdekaLiburan Promo! Join the fun and get up to Rp77k discount for Car Rental now. Moreover, get special price cut of up to 30%, only on your lifestyle superapp. Find more details about this promo below. Booking period:  9 – 17 August 2022', 'https://www.traveloka.com/en-id/promotion/merdeka-rental', NULL, NULL, '', 'akomodasi', '30%', '', 'car', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `promo`
--
ALTER TABLE `promo`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `promo`
--
ALTER TABLE `promo`
  MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8780;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
